
package pe.edu.ucv.examen.view;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import pe.edu.ucv.examen.AccesoBD.AccesoBD;
import pe.edu.ucv.examen.AccesoBD.CargarTablaventaSQL;
import pe.edu.ucv.examen.model.CajasdeTextoModel;
import pe.edu.ucv.examen.model.Llenarcomboventas;
import pe.edu.ucv.examen.model.ModelTabla;
import pe.edu.ucv.examen.service.AgregarVenta;


/**
 *
 * @author User
 */
public class RegistrodeVenta extends javax.swing.JPanel {
    AgregarVenta agregarventa = new AgregarVenta();
    Llenarcomboventas comboventas = new Llenarcomboventas();
     ModelTabla model = new ModelTabla();
     private DefaultTableModel modelito;
      CargarTablaventaSQL ventaDAO = new CargarTablaventaSQL();
CajasdeTextoModel cajasdetexto = new CajasdeTextoModel();
    public RegistrodeVenta() {
        initComponents();
        modelito = new DefaultTableModel();
        model.inicializarModelo(modelito);        
        cajasdetexto.DesactivarCajas(txtIDCompra, txtPrecio,
        txtSubtotal, txtTotal, txtTotalFinal, txtImpuesto,txtFecha);   
        tblDatos.setModel(modelito);
        cargarDatosProductos();
        cargarDatosDesdeDAO();
        txtCantidad.getDocument().addDocumentListener(new MyDocumentListener());
        txtPrecio.getDocument().addDocumentListener(new MyDocumentListener());
        txtDescuento.getDocument().addDocumentListener(new MyDocumentListener());    
        txtFecha.setText(fechaactual());
       
    }
    
  private void cargarDatosProductos() {
        comboventas.PonerDatosCBXProducto(cbxproducto);
    }

    private void cargarDatosDesdeDAO() {
      ventaDAO.cargarDatosEnTabla(modelito, txtTotalFinal, txtIDCompra); 
    }
  
       public class MyDocumentListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            calcularResultado();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            calcularResultado();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            calcularResultado();
        }

       private void calcularResultado() {
    try {
        int num1 = (txtCantidad.getText().isEmpty()) ? 1 : Integer.parseInt(txtCantidad.getText());
        double num2 = (txtPrecio.getText().isEmpty()) ? 1 : Double.parseDouble(txtPrecio.getText());
        double num3 = (txtDescuento.getText().isEmpty() || txtDescuento.getText().equals("0")) ? 1 : Double.parseDouble(txtDescuento.getText());         
        double resultado = num1 * num2;
        double descuento = (num3 / 100);
        double result = (resultado * descuento);
        double TOTAL = (resultado - result);
        txtSubtotal.setText(String.valueOf(resultado));
        txtTotal.setText(String.valueOf(TOTAL));
    } catch (NumberFormatException ex) {
        txtSubtotal.setText("Error");
        txtTotal.setText("Error");
    }
}
//      private void cargarDatosDesdeDAO() {      
//
//        // Llama al método cargarDatosEnTabla con los parámetros necesarios
//        ventaDAO.cargarDatosEnTabla(modelito, txtTotalFinal, txtIDCompra);
//    }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelFondo = new javax.swing.JPanel();
        PanelUp = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtnGuardar = new javax.swing.JButton();
        jbtnactualizar = new javax.swing.JButton();
        txtIDCompra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbxproducto = new javax.swing.JComboBox<>();
        txtFecha = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtImpuesto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnAgregarATabla = new javax.swing.JButton();
        PanelDown = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtTotalFinal = new javax.swing.JTextField();
        btnQuitarDeTabla = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFondo.setBackground(new java.awt.Color(204, 204, 204));
        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelUp.setBackground(new java.awt.Color(153, 0, 255));
        PanelUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE COMPRAS");
        PanelUp.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        PanelFondo.add(PanelUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes4/verificar.png"))); // NOI18N
        jbtnGuardar.setText("Guardar");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 60));

        jbtnactualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes4/editar.png"))); // NOI18N
        jbtnactualizar.setText("Actualizar ");
        jbtnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnactualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 150, 60));

        txtIDCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtIDCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID COMPRA:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, -1, -1));

        PanelFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1160, 60));

        jPanel3.setBackground(new java.awt.Color(153, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Total:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Producto:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Cantidad:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Precio:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Descuento:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Subtotal:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Impuesto:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, -1, -1));

        cbxproducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----Seleccione----" }));
        cbxproducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxproductoItemStateChanged(evt);
            }
        });
        jPanel3.add(cbxproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, 40));

        txtFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 40));

        txtCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 90, 40));

        txtPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 100, 40));

        txtDescuento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 100, 40));

        txtSubtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 110, 40));

        txtImpuesto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 110, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Fecha:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 130, 40));

        btnAgregarATabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes4/anadir-al-carrito.png"))); // NOI18N
        btnAgregarATabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarATablaActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregarATabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 130, 60, -1));

        PanelFondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1160, 180));

        PanelDown.setBackground(new java.awt.Color(255, 204, 255));
        PanelDown.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT", "CANTIDAD", "PRECIO", "DESCUENTO", "SUBTOTAL", "IMPUESTO", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        PanelDown.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1010, 200));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("TOTAL");
        PanelDown.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, -1, -1));

        txtTotalFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelDown.add(txtTotalFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, 150, 40));

        btnQuitarDeTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes4/borrar.png"))); // NOI18N
        btnQuitarDeTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarDeTablaActionPerformed(evt);
            }
        });
        PanelDown.add(btnQuitarDeTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 60, 50));

        PanelFondo.add(PanelDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 1160, 310));

        jPanel1.add(PanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        for (int i = 0; i < modelito.getRowCount(); i++) {
            String Datos[] = new String[7];
            Datos[0] = tblDatos.getValueAt(i, 0).toString();
            Datos[1] = tblDatos.getValueAt(i, 1).toString();
            Datos[2] = tblDatos.getValueAt(i, 2).toString();
            Datos[3] = tblDatos.getValueAt(i, 3).toString();
            Datos[4] = tblDatos.getValueAt(i, 4).toString();
            Datos[5] = tblDatos.getValueAt(i, 5).toString();
            Datos[6] = tblDatos.getValueAt(i, 6).toString();            
            agregarventa.insertarDatosProcedimientoAlmacenado(Datos);                 }   
        DefaultTableModel model = (DefaultTableModel) tblDatos.getModel();
        model.setRowCount(0);                
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void btnAgregarATablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarATablaActionPerformed
        String producto = (String) cbxproducto.getSelectedItem();
        String cantidad = txtCantidad.getText();
        float precio = Float.parseFloat(txtPrecio.getText());
        String descuento = txtDescuento.getText();
        String subtotal = txtSubtotal.getText();
        String impuesto = txtImpuesto.getText();
        String total = txtTotal.getText();
        
        Object[] fila = {producto, cantidad, precio, descuento, subtotal, impuesto, total};
        modelito.addRow(fila);
        ModelTabla limpiar = new  ModelTabla();
        limpiar.limpiarCampos(txtCantidad,  txtDescuento, 
                txtSubtotal, txtImpuesto, txtTotal);
    }//GEN-LAST:event_btnAgregarATablaActionPerformed

    private void btnQuitarDeTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarDeTablaActionPerformed
     int com;

        com = tblDatos.getSelectedRow();
        if (com == -1) {
            JOptionPane.showMessageDialog(null, "Seleccionar el producto a eliminar");
        } else {
            modelito.removeRow(com);
        }
    }//GEN-LAST:event_btnQuitarDeTablaActionPerformed

    private void cbxproductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxproductoItemStateChanged
      String prod = (String) cbxproducto.getSelectedItem();
      String consultaprecio = "SELECT precio FROM Producto WHERE nombre = ?";
      Connection con = null; // Declarar la conexión
    try{
          con = AccesoBD.getConexion();
    }catch (SQLException ex) {
            ex.printStackTrace();   }
        try (PreparedStatement statement = con.prepareStatement(consultaprecio)) {
            statement.setString(1, prod);
            ResultSet resultSet = statement.executeQuery();
            if (resultSet.next()) {
                Double precio = resultSet.getDouble("precio");
                txtPrecio.setText(String.valueOf(precio));        }
        } catch (SQLException ex) {
            ex.printStackTrace();     }
    }//GEN-LAST:event_cbxproductoItemStateChanged

    private void jbtnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnactualizarActionPerformed
  int row = tblDatos.getSelectedRow();
// Asegúrate de que haya una fila seleccionada
    if (row != -1) {
    // Obtiene los valores de la fila seleccionada
   String nuevoProducto = cbxproducto.getSelectedItem().toString();
    String cantidad = txtCantidad.getText().trim(); 
    String descuento = txtDescuento.getText().trim();
    String subtotal = txtSubtotal.getText().trim();
    String total = txtTotal.getText().trim();

    // Actualiza los valores directamente en el modelo
    modelito.setValueAt(nuevoProducto, row, 0);
    modelito.setValueAt(cantidad, row, 1);
    modelito.setValueAt(descuento, row, 3);
    modelito.setValueAt(subtotal, row, 4);
    modelito.setValueAt(total, row, 6);
      int nuevoIndice = obtenerIndiceEnComboBox(nuevoProducto, cbxproducto);
    cbxproducto.setSelectedIndex(nuevoIndice);
}
  
   ModelTabla limpiar = new  ModelTabla();
    limpiar.limpiarCampos(txtCantidad, txtDescuento, 
                txtSubtotal, txtImpuesto, txtTotal);
    }//GEN-LAST:event_jbtnactualizarActionPerformed

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
    txtCantidad.setText(modelito.getValueAt(tblDatos.getSelectedRow(), 1).toString());
    txtDescuento.setText(modelito.getValueAt(tblDatos.getSelectedRow(), 3).toString());
   String productoNombre = (String) modelito.getValueAt(tblDatos.getSelectedRow(), 0);

// Seleccionar el producto en el JComboBox
cbxproducto.setSelectedItem(productoNombre);
   
    }//GEN-LAST:event_tblDatosMouseClicked
private int obtenerIndiceEnComboBox(String elemento, JComboBox<String> comboBox) {
    for (int i = 0; i < comboBox.getItemCount(); i++) {
        if (comboBox.getItemAt(i).equals(elemento)) {
            return i;
        }
    }
    return -1;
}
 public static String fechaactual(){
     Date fecha = new Date();
     SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
     return formatofecha.format(fecha);
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDown;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel PanelUp;
    private javax.swing.JButton btnAgregarATabla;
    private javax.swing.JButton btnQuitarDeTabla;
    private javax.swing.JComboBox<String> cbxproducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnactualizar;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIDCompra;
    private javax.swing.JTextField txtImpuesto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalFinal;
    // End of variables declaration//GEN-END:variables
}
